/**
 * 中国常见食物营养成分数据库
 * 数据参考《中国食物成分表》标准值，每100g可食部分
 * 字段: name, emoji, carb(碳水g), protein(蛋白质g), fat(脂肪g), cat(分类)
 */
const FOOD_DB = [
  // ==================== 谷薯类 ====================
  { name:'大米(生)', emoji:'🍚', carb:77.2, protein:7.4, fat:0.8, cat:'谷薯类' },
  { name:'糙米(生)', emoji:'🍚', carb:73, protein:7.5, fat:2.7, cat:'谷薯类' },
  { name:'白米饭(熟)', emoji:'🍚', carb:25.6, protein:2.6, fat:0.3, cat:'谷薯类' },
  { name:'糙米饭(熟)', emoji:'🍚', carb:23.3, protein:2.8, fat:0.9, cat:'谷薯类' },
  { name:'小米(生)', emoji:'🌾', carb:72.0, protein:9.0, fat:3.1, cat:'谷薯类' },
  { name:'小米粥', emoji:'🥣', carb:8.4, protein:1.4, fat:0.7, cat:'谷薯类' },
  { name:'燕麦(生)', emoji:'🥣', carb:61.6, protein:13.2, fat:6.4, cat:'谷薯类' },
  { name:'燕麦片(即食)', emoji:'🥣', carb:59.8, protein:12.0, fat:7.0, cat:'谷薯类' },
  { name:'玉米(鲜)', emoji:'🌽', carb:19.9, protein:3.8, fat:1.2, cat:'谷薯类' },
  { name:'玉米面(生)', emoji:'🌽', carb:70.4, protein:8.1, fat:3.3, cat:'谷薯类' },
  { name:'全麦面粉', emoji:'🌾', carb:67.8, protein:12.5, fat:1.8, cat:'谷薯类' },
  { name:'白面粉', emoji:'🌾', carb:73.6, protein:11.2, fat:1.5, cat:'谷薯类' },
  { name:'面条(生)', emoji:'🍜', carb:61.9, protein:8.5, fat:1.6, cat:'谷薯类' },
  { name:'面条(熟)', emoji:'🍜', carb:24.3, protein:3.4, fat:0.6, cat:'谷薯类' },
  { name:'全麦面包', emoji:'🍞', carb:43.0, protein:9.0, fat:3.4, cat:'谷薯类' },
  { name:'白面包', emoji:'🍞', carb:48.6, protein:8.3, fat:3.8, cat:'谷薯类' },
  { name:'馒头', emoji:'🫓', carb:47.0, protein:7.0, fat:1.1, cat:'谷薯类' },
  { name:'花卷', emoji:'🫓', carb:45.6, protein:6.8, fat:2.5, cat:'谷薯类' },
  { name:'包子皮', emoji:'🫓', carb:44.0, protein:7.2, fat:1.2, cat:'谷薯类' },
  { name:'饺子皮', emoji:'🥟', carb:46.7, protein:8.0, fat:0.6, cat:'谷薯类' },
  { name:'米粉(生)', emoji:'🍜', carb:82.0, protein:3.7, fat:0.3, cat:'谷薯类' },
  { name:'米粉(熟)', emoji:'🍜', carb:25.0, protein:1.2, fat:0.1, cat:'谷薯类' },
  { name:'年糕', emoji:'🍡', carb:50.3, protein:3.3, fat:0.6, cat:'谷薯类' },
  { name:'粽子(白)', emoji:'🫔', carb:36.5, protein:4.2, fat:1.0, cat:'谷薯类' },
  { name:'红薯', emoji:'🍠', carb:21.0, protein:1.6, fat:0.1, cat:'谷薯类' },
  { name:'紫薯', emoji:'🍠', carb:18.0, protein:1.3, fat:0.2, cat:'谷薯类' },
  { name:'土豆', emoji:'🥔', carb:16.5, protein:2.0, fat:0.2, cat:'谷薯类' },
  { name:'山药', emoji:'🥔', carb:12.4, protein:1.5, fat:0.2, cat:'谷薯类' },
  { name:'芋头', emoji:'🥔', carb:18.1, protein:1.3, fat:0.2, cat:'谷薯类' },
  { name:'南瓜', emoji:'🎃', carb:5.3, protein:0.7, fat:0.1, cat:'谷薯类' },
  { name:'藕', emoji:'🥔', carb:16.4, protein:1.2, fat:0.2, cat:'谷薯类' },

  // ==================== 畜肉类 ====================
  { name:'猪瘦肉', emoji:'🥩', carb:0.7, protein:20.3, fat:6.2, cat:'畜肉类' },
  { name:'猪五花肉', emoji:'🥩', carb:0.4, protein:13.2, fat:30.6, cat:'畜肉类' },
  { name:'猪里脊', emoji:'🥩', carb:0.1, protein:20.2, fat:7.9, cat:'畜肉类' },
  { name:'猪排骨', emoji:'🍖', carb:0, protein:16.7, fat:20.4, cat:'畜肉类' },
  { name:'猪肝', emoji:'🫀', carb:2.6, protein:19.3, fat:3.5, cat:'畜肉类' },
  { name:'猪蹄', emoji:'🍖', carb:0, protein:17.0, fat:18.8, cat:'畜肉类' },
  { name:'猪肉松', emoji:'🥩', carb:4.1, protein:41.8, fat:10.2, cat:'畜肉类' },
  { name:'牛肉(瘦)', emoji:'🥩', carb:0, protein:20.2, fat:4.2, cat:'畜肉类' },
  { name:'牛腱子肉', emoji:'🥩', carb:0, protein:21.5, fat:2.8, cat:'畜肉类' },
  { name:'牛肋肉', emoji:'🥩', carb:0, protein:17.1, fat:14.4, cat:'畜肉类' },
  { name:'肥牛卷', emoji:'🥩', carb:0, protein:14.0, fat:24.6, cat:'畜肉类' },
  { name:'牛肉干', emoji:'🥩', carb:6.0, protein:45.6, fat:8.0, cat:'畜肉类' },
  { name:'羊肉(瘦)', emoji:'🥩', carb:0, protein:19.0, fat:14.1, cat:'畜肉类' },
  { name:'羊腿肉', emoji:'🍖', carb:0, protein:18.2, fat:9.8, cat:'畜肉类' },
  { name:'兔肉', emoji:'🐰', carb:0, protein:19.7, fat:2.2, cat:'畜肉类' },
  { name:'驴肉', emoji:'🥩', carb:0.4, protein:21.5, fat:3.2, cat:'畜肉类' },

  // ==================== 禽肉类 ====================
  { name:'鸡胸肉', emoji:'🍗', carb:0, protein:24.6, fat:1.9, cat:'禽肉类' },
  { name:'鸡腿肉', emoji:'🍗', carb:0, protein:18.8, fat:9.6, cat:'禽肉类' },
  { name:'鸡翅', emoji:'🍗', carb:0, protein:17.4, fat:11.8, cat:'禽肉类' },
  { name:'鸡全翅(炸)', emoji:'🍗', carb:7.0, protein:18.2, fat:16.5, cat:'禽肉类' },
  { name:'琵琶腿', emoji:'🍗', carb:0, protein:16.0, fat:13.2, cat:'禽肉类' },
  { name:'鸡肝', emoji:'🫀', carb:1.4, protein:16.6, fat:4.6, cat:'禽肉类' },
  { name:'鸡爪', emoji:'🐔', carb:0, protein:16.4, fat:9.6, cat:'禽肉类' },
  { name:'鸡皮', emoji:'🐔', carb:0, protein:10.1, fat:35.3, cat:'禽肉类' },
  { name:'鸭肉', emoji:'🦆', carb:0, protein:15.5, fat:19.7, cat:'禽肉类' },
  { name:'鸭胸肉', emoji:'🦆', carb:0, protein:19.8, fat:7.5, cat:'禽肉类' },
  { name:'鹅肉', emoji:'🦢', carb:0, protein:17.9, fat:11.2, cat:'禽肉类' },
  { name:'火鸡胸', emoji:'🦃', carb:0, protein:24.5, fat:1.0, cat:'禽肉类' },

  // ==================== 水产海鲜 ====================
  { name:'鲈鱼', emoji:'🐟', carb:0, protein:18.6, fat:3.4, cat:'水产海鲜' },
  { name:'草鱼', emoji:'🐟', carb:0, protein:16.6, fat:5.2, cat:'水产海鲜' },
  { name:'鲫鱼', emoji:'🐟', carb:0, protein:17.1, fat:2.7, cat:'水产海鲜' },
  { name:'鳕鱼', emoji:'🐟', carb:0, protein:20.4, fat:0.6, cat:'水产海鲜' },
  { name:'龙利鱼', emoji:'🐟', carb:0, protein:14.4, fat:1.2, cat:'水产海鲜' },
  { name:'带鱼', emoji:'🐟', carb:0, protein:17.7, fat:4.9, cat:'水产海鲜' },
  { name:'三文鱼', emoji:'🐠', carb:0, protein:20.0, fat:13.0, cat:'水产海鲜' },
  { name:'金枪鱼(罐)', emoji:'🐠', carb:0, protein:26.0, fat:0.8, cat:'水产海鲜' },
  { name:'秋刀鱼', emoji:'🐟', carb:0, protein:18.0, fat:18.8, cat:'水产海鲜' },
  { name:'虾仁', emoji:'🦐', carb:0.7, protein:18.6, fat:0.8, cat:'水产海鲜' },
  { name:'基围虾', emoji:'🦐', carb:0, protein:18.2, fat:1.4, cat:'水产海鲜' },
  { name:'对虾', emoji:'🦐', carb:0, protein:20.6, fat:0.7, cat:'水产海鲜' },
  { name:'皮皮虾', emoji:'🦐', carb:0, protein:17.2, fat:2.4, cat:'水产海鲜' },
  { name:'螃蟹', emoji:'🦀', carb:0, protein:17.5, fat:2.6, cat:'水产海鲜' },
  { name:'蛤蜊', emoji:'🐚', carb:2.0, protein:10.1, fat:1.1, cat:'水产海鲜' },
  { name:'扇贝(鲜)', emoji:'🐚', carb:2.6, protein:11.1, fat:0.6, cat:'水产海鲜' },
  { name:'鱿鱼', emoji:'🦑', carb:1.8, protein:17.0, fat:1.2, cat:'水产海鲜' },
  { name:'章鱼', emoji:'🐙', carb:0, protein:18.9, fat:0.8, cat:'水产海鲜' },
  { name:'海参', emoji:'🌊', carb:0.4, protein:16.5, fat:0.2, cat:'水产海鲜' },
  { name:'生蚝', emoji:'🦪', carb:5.7, protein:5.7, fat:1.6, cat:'水产海鲜' },
  { name:'海带(湿)', emoji:'🌊', carb:2.1, protein:1.2, fat:0.1, cat:'水产海鲜' },
  { name:'紫菜(干)', emoji:'🌊', carb:21.6, protein:26.7, fat:1.1, cat:'水产海鲜' },

  // ==================== 蛋奶类 ====================
  { name:'鸡蛋(全)', emoji:'🥚', carb:1.5, protein:13.0, fat:10.0, cat:'蛋奶类' },
  { name:'鸡蛋白', emoji:'🥚', carb:0.7, protein:11.0, fat:0.2, cat:'蛋奶类' },
  { name:'鸡蛋黄', emoji:'🟡', carb:0.6, protein:15.9, fat:28.2, cat:'蛋奶类' },
  { name:'鹌鹑蛋', emoji:'🥚', carb:0.6, protein:12.8, fat:11.1, cat:'蛋奶类' },
  { name:'鸭蛋', emoji:'🥚', carb:0, protein:12.6, fat:13.0, cat:'蛋奶类' },
  { name:'咸鸭蛋', emoji:'🥚', carb:3.1, protein:12.7, fat:12.7, cat:'蛋奶类' },
  { name:'牛奶(全脂)', emoji:'🥛', carb:4.8, protein:3.2, fat:3.6, cat:'蛋奶类' },
  { name:'牛奶(脱脂)', emoji:'🥛', carb:5.0, protein:3.4, fat:0.1, cat:'蛋奶类' },
  { name:'酸奶(原味)', emoji:'🥛', carb:10.0, protein:3.5, fat:3.0, cat:'蛋奶类' },
  { name:'希腊酸奶', emoji:'🥛', carb:4.0, protein:9.0, fat:5.0, cat:'蛋奶类' },
  { name:'奶酪片', emoji:'🧀', carb:2.5, protein:20.0, fat:26.0, cat:'蛋奶类' },
  { name:'马苏里拉', emoji:'🧀', carb:2.2, protein:22.2, fat:22.4, cat:'蛋奶类' },
  { name:'奶油(淡)', emoji:'🧈', carb:3.3, protein:2.5, fat:33.0, cat:'蛋奶类' },
  { name:'炼乳', emoji:'🥛', carb:55.0, protein:8.0, fat:8.5, cat:'蛋奶类' },
  { name:'乳清蛋白粉', emoji:'💪', carb:5.0, protein:78.0, fat:3.0, cat:'蛋奶类' },

  // ==================== 豆制品 ====================
  { name:'黄豆(干)', emoji:'🫘', carb:18.7, protein:35.1, fat:16.0, cat:'豆制品' },
  { name:'豆浆(无糖)', emoji:'🥛', carb:1.2, protein:3.6, fat:1.8, cat:'豆制品' },
  { name:'豆腐(南)', emoji:'🧈', carb:2.7, protein:6.2, fat:3.7, cat:'豆制品' },
  { name:'豆腐(北)', emoji:'🧈', carb:1.5, protein:12.2, fat:4.8, cat:'豆制品' },
  { name:'豆腐干', emoji:'🧈', carb:4.9, protein:16.2, fat:3.6, cat:'豆制品' },
  { name:'腐竹(干)', emoji:'🧈', carb:12.5, protein:44.6, fat:21.7, cat:'豆制品' },
  { name:'豆腐皮', emoji:'🧈', carb:3.4, protein:23.7, fat:12.8, cat:'豆制品' },
  { name:'千张', emoji:'🧈', carb:5.2, protein:24.5, fat:13.9, cat:'豆制品' },
  { name:'毛豆(鲜)', emoji:'🫛', carb:4.9, protein:13.1, fat:5.0, cat:'豆制品' },
  { name:'豆芽(绿豆)', emoji:'🌱', carb:2.9, protein:2.6, fat:0.1, cat:'豆制品' },
  { name:'黑豆(干)', emoji:'🫘', carb:20.2, protein:36.0, fat:15.9, cat:'豆制品' },
  { name:'红豆(干)', emoji:'🫘', carb:55.7, protein:20.2, fat:0.6, cat:'豆制品' },

  // ==================== 蔬菜类 ====================
  { name:'西蓝花', emoji:'🥦', carb:4.3, protein:3.5, fat:0.4, cat:'蔬菜类' },
  { name:'菜花', emoji:'🥦', carb:4.4, protein:2.1, fat:0.2, cat:'蔬菜类' },
  { name:'菠菜', emoji:'🥬', carb:3.6, protein:2.9, fat:0.4, cat:'蔬菜类' },
  { name:'生菜', emoji:'🥗', carb:1.3, protein:1.3, fat:0.3, cat:'蔬菜类' },
  { name:'油麦菜', emoji:'🥬', carb:2.1, protein:1.7, fat:0.4, cat:'蔬菜类' },
  { name:'小白菜', emoji:'🥬', carb:2.4, protein:1.5, fat:0.3, cat:'蔬菜类' },
  { name:'大白菜', emoji:'🥬', carb:2.6, protein:1.5, fat:0.1, cat:'蔬菜类' },
  { name:'空心菜', emoji:'🥬', carb:2.2, protein:2.2, fat:0.3, cat:'蔬菜类' },
  { name:'娃娃菜', emoji:'🥬', carb:2.5, protein:1.6, fat:0.1, cat:'蔬菜类' },
  { name:'韭菜', emoji:'🌿', carb:3.2, protein:2.4, fat:0.4, cat:'蔬菜类' },
  { name:'芹菜', emoji:'🥬', carb:2.0, protein:0.7, fat:0.1, cat:'蔬菜类' },
  { name:'黄瓜', emoji:'🥒', carb:2.9, protein:0.7, fat:0.1, cat:'蔬菜类' },
  { name:'番茄', emoji:'🍅', carb:3.9, protein:0.9, fat:0.2, cat:'蔬菜类' },
  { name:'茄子', emoji:'🍆', carb:4.9, protein:1.1, fat:0.2, cat:'蔬菜类' },
  { name:'辣椒(青)', emoji:'🌶️', carb:5.4, protein:1.0, fat:0.2, cat:'蔬菜类' },
  { name:'彩椒', emoji:'🫑', carb:6.0, protein:0.9, fat:0.2, cat:'蔬菜类' },
  { name:'西葫芦', emoji:'🥒', carb:2.6, protein:0.8, fat:0.2, cat:'蔬菜类' },
  { name:'冬瓜', emoji:'🥒', carb:2.6, protein:0.4, fat:0.2, cat:'蔬菜类' },
  { name:'苦瓜', emoji:'🥒', carb:3.5, protein:1.0, fat:0.1, cat:'蔬菜类' },
  { name:'丝瓜', emoji:'🥒', carb:4.2, protein:1.0, fat:0.2, cat:'蔬菜类' },
  { name:'豆角', emoji:'🫛', carb:5.7, protein:2.5, fat:0.2, cat:'蔬菜类' },
  { name:'胡萝卜', emoji:'🥕', carb:8.1, protein:1.0, fat:0.2, cat:'蔬菜类' },
  { name:'白萝卜', emoji:'🥕', carb:4.2, protein:0.7, fat:0.1, cat:'蔬菜类' },
  { name:'洋葱', emoji:'🧅', carb:8.0, protein:1.1, fat:0.2, cat:'蔬菜类' },
  { name:'蒜薹', emoji:'🧄', carb:6.4, protein:2.5, fat:0.4, cat:'蔬菜类' },
  { name:'大葱', emoji:'🧅', carb:6.5, protein:1.6, fat:0.3, cat:'蔬菜类' },
  { name:'莴笋', emoji:'🥬', carb:1.7, protein:0.6, fat:0.1, cat:'蔬菜类' },
  { name:'竹笋', emoji:'🎋', carb:2.2, protein:2.6, fat:0.2, cat:'蔬菜类' },
  { name:'蘑菇(平菇)', emoji:'🍄', carb:4.6, protein:2.3, fat:0.3, cat:'蔬菜类' },
  { name:'香菇(鲜)', emoji:'🍄', carb:5.2, protein:2.2, fat:0.3, cat:'蔬菜类' },
  { name:'金针菇', emoji:'🍄', carb:3.3, protein:2.4, fat:0.3, cat:'蔬菜类' },
  { name:'杏鲍菇', emoji:'🍄', carb:5.1, protein:1.3, fat:0.1, cat:'蔬菜类' },
  { name:'木耳(泡发)', emoji:'🍄', carb:6.0, protein:1.5, fat:0.2, cat:'蔬菜类' },
  { name:'秋葵', emoji:'🌿', carb:5.7, protein:2.0, fat:0.1, cat:'蔬菜类' },
  { name:'芦笋', emoji:'🌿', carb:2.4, protein:2.0, fat:0.2, cat:'蔬菜类' },

  // ==================== 水果类 ====================
  { name:'苹果', emoji:'🍎', carb:12.3, protein:0.2, fat:0.2, cat:'水果类' },
  { name:'香蕉', emoji:'🍌', carb:22.0, protein:1.4, fat:0.2, cat:'水果类' },
  { name:'橙子', emoji:'🍊', carb:11.1, protein:0.8, fat:0.2, cat:'水果类' },
  { name:'柚子', emoji:'🍊', carb:9.0, protein:0.8, fat:0.2, cat:'水果类' },
  { name:'葡萄', emoji:'🍇', carb:17.2, protein:0.5, fat:0.2, cat:'水果类' },
  { name:'草莓', emoji:'🍓', carb:7.1, protein:1.0, fat:0.2, cat:'水果类' },
  { name:'蓝莓', emoji:'🫐', carb:14.5, protein:0.7, fat:0.3, cat:'水果类' },
  { name:'猕猴桃', emoji:'🥝', carb:11.9, protein:0.8, fat:0.6, cat:'水果类' },
  { name:'芒果', emoji:'🥭', carb:15.0, protein:0.6, fat:0.3, cat:'水果类' },
  { name:'菠萝', emoji:'🍍', carb:10.8, protein:0.5, fat:0.1, cat:'水果类' },
  { name:'西瓜', emoji:'🍉', carb:5.8, protein:0.6, fat:0.1, cat:'水果类' },
  { name:'哈密瓜', emoji:'🍈', carb:7.9, protein:0.4, fat:0.1, cat:'水果类' },
  { name:'梨', emoji:'🍐', carb:13.3, protein:0.1, fat:0.2, cat:'水果类' },
  { name:'桃', emoji:'🍑', carb:10.9, protein:0.9, fat:0.1, cat:'水果类' },
  { name:'樱桃', emoji:'🍒', carb:12.0, protein:1.1, fat:0.2, cat:'水果类' },
  { name:'榴莲', emoji:'🥝', carb:27.1, protein:2.6, fat:3.3, cat:'水果类' },
  { name:'牛油果', emoji:'🥑', carb:8.5, protein:2.0, fat:14.7, cat:'水果类' },
  { name:'火龙果', emoji:'🍈', carb:13.3, protein:1.1, fat:0.2, cat:'水果类' },
  { name:'柿子', emoji:'🍊', carb:18.5, protein:0.7, fat:0.1, cat:'水果类' },
  { name:'龙眼(鲜)', emoji:'🍈', carb:16.2, protein:1.2, fat:0.1, cat:'水果类' },
  { name:'荔枝', emoji:'🍈', carb:16.1, protein:0.9, fat:0.2, cat:'水果类' },
  { name:'柠檬', emoji:'🍋', carb:6.2, protein:1.1, fat:1.2, cat:'水果类' },

  // ==================== 坚果种子 ====================
  { name:'花生(生)', emoji:'🥜', carb:12.0, protein:24.8, fat:44.3, cat:'坚果种子' },
  { name:'花生(熟)', emoji:'🥜', carb:13.0, protein:23.9, fat:48.0, cat:'坚果种子' },
  { name:'花生酱', emoji:'🥜', carb:20.0, protein:25.2, fat:53.0, cat:'坚果种子' },
  { name:'核桃', emoji:'🌰', carb:9.6, protein:14.9, fat:58.8, cat:'坚果种子' },
  { name:'杏仁', emoji:'🌰', carb:10.0, protein:21.0, fat:50.0, cat:'坚果种子' },
  { name:'腰果', emoji:'🌰', carb:30.2, protein:18.2, fat:43.8, cat:'坚果种子' },
  { name:'开心果', emoji:'🌰', carb:18.0, protein:20.2, fat:45.3, cat:'坚果种子' },
  { name:'夏威夷果', emoji:'🌰', carb:13.8, protein:7.9, fat:75.8, cat:'坚果种子' },
  { name:'榛子', emoji:'🌰', carb:14.7, protein:13.7, fat:52.0, cat:'坚果种子' },
  { name:'松子', emoji:'🌰', carb:4.5, protein:13.4, fat:62.6, cat:'坚果种子' },
  { name:'瓜子(葵花)', emoji:'🌻', carb:10.0, protein:19.1, fat:52.8, cat:'坚果种子' },
  { name:'南瓜子', emoji:'🌻', carb:4.5, protein:29.0, fat:46.7, cat:'坚果种子' },
  { name:'芝麻(黑)', emoji:'⚫', carb:10.0, protein:19.1, fat:46.1, cat:'坚果种子' },
  { name:'芝麻(白)', emoji:'⚪', carb:8.8, protein:18.4, fat:52.5, cat:'坚果种子' },
  { name:'奇亚籽', emoji:'🌱', carb:7.7, protein:16.5, fat:30.7, cat:'坚果种子' },
  { name:'亚麻籽', emoji:'🌱', carb:1.6, protein:18.3, fat:42.2, cat:'坚果种子' },
  { name:'混合坚果', emoji:'🥜', carb:15.0, protein:18.0, fat:52.0, cat:'坚果种子' },

  // ==================== 油脂调味 ====================
  { name:'橄榄油', emoji:'🫒', carb:0, protein:0, fat:99.9, cat:'油脂调味' },
  { name:'椰子油', emoji:'🥥', carb:0, protein:0, fat:99.9, cat:'油脂调味' },
  { name:'菜籽油', emoji:'🫒', carb:0, protein:0, fat:99.9, cat:'油脂调味' },
  { name:'花生油', emoji:'🫒', carb:0, protein:0, fat:99.9, cat:'油脂调味' },
  { name:'大豆油', emoji:'🫒', carb:0, protein:0, fat:99.9, cat:'油脂调味' },
  { name:'玉米油', emoji:'🫒', carb:0, protein:0, fat:99.9, cat:'油脂调味' },
  { name:'亚麻籽油', emoji:'🫒', carb:0, protein:0, fat:99.9, cat:'油脂调味' },
  { name:'芝麻油', emoji:'🫒', carb:0, protein:0, fat:99.9, cat:'油脂调味' },
  { name:'黄油', emoji:'🧈', carb:0.5, protein:0.7, fat:81.1, cat:'油脂调味' },
  { name:'猪油', emoji:'🧈', carb:0, protein:0, fat:99.6, cat:'油脂调味' },
  { name:'沙拉酱', emoji:'🥫', carb:4.5, protein:0.8, fat:62.0, cat:'油脂调味' },
  { name:'蚝油', emoji:'🥫', carb:16.2, protein:2.4, fat:0.2, cat:'油脂调味' },
  { name:'生抽', emoji:'🥫', carb:8.6, protein:8.3, fat:0.1, cat:'油脂调味' },
  { name:'老抽', emoji:'🥫', carb:14.5, protein:5.6, fat:0.1, cat:'油脂调味' },
  { name:'醋', emoji:'🥫', carb:4.9, protein:0.6, fat:0.1, cat:'油脂调味' },
  { name:'番茄酱', emoji:'🥫', carb:18.9, protein:1.6, fat:0.2, cat:'油脂调味' },
  { name:'辣椒酱', emoji:'🌶️', carb:11.0, protein:3.5, fat:7.0, cat:'油脂调味' },
  { name:'白砂糖', emoji:'🧂', carb:99.5, protein:0, fat:0, cat:'油脂调味' },
  { name:'蜂蜜', emoji:'🍯', carb:75.6, protein:0.4, fat:1.9, cat:'油脂调味' },

  // ==================== 加工/即食 ====================
  { name:'火腿肠', emoji:'🌭', carb:7.8, protein:10.4, fat:13.2, cat:'加工即食' },
  { name:'午餐肉(罐)', emoji:'🥫', carb:5.1, protein:15.0, fat:17.0, cat:'加工即食' },
  { name:'培根', emoji:'🥓', carb:0.7, protein:14.6, fat:35.0, cat:'加工即食' },
  { name:'香肠', emoji:'🌭', carb:6.5, protein:14.0, fat:25.0, cat:'加工即食' },
  { name:'烤鸡腿', emoji:'🍗', carb:2.0, protein:22.0, fat:12.0, cat:'加工即食' },
  { name:'煎牛排', emoji:'🥩', carb:0, protein:25.8, fat:10.2, cat:'加工即食' },
  { name:'水煮鸡蛋', emoji:'🥚', carb:1.5, protein:12.7, fat:10.0, cat:'加工即食' },
  { name:'茶叶蛋', emoji:'🥚', carb:1.9, protein:12.4, fat:9.5, cat:'加工即食' },
  { name:'煎蛋', emoji:'🍳', carb:1.0, protein:11.6, fat:14.0, cat:'加工即食' },
  { name:'饺子(猪肉)', emoji:'🥟', carb:22.0, protein:7.6, fat:6.5, cat:'加工即食' },
  { name:'包子(猪肉)', emoji:'🫓', carb:28.0, protein:8.0, fat:5.5, cat:'加工即食' },
  { name:'煎饼果子', emoji:'🫓', carb:30.0, protein:6.0, fat:8.0, cat:'加工即食' },
  { name:'方便面(干)', emoji:'🍜', carb:57.0, protein:9.5, fat:21.1, cat:'加工即食' },
  { name:'粉丝(干)', emoji:'🍜', carb:83.7, protein:0.2, fat:0.1, cat:'加工即食' },
  { name:'凉皮', emoji:'🍜', carb:25.0, protein:3.8, fat:1.0, cat:'加工即食' },
  { name:'油条', emoji:'🫓', carb:37.5, protein:6.9, fat:17.6, cat:'加工即食' },

  // ==================== 饮品冲调 ====================
  { name:'可乐', emoji:'🥤', carb:10.6, protein:0, fat:0, cat:'饮品冲调' },
  { name:'橙汁(鲜榨)', emoji:'🧃', carb:10.5, protein:0.7, fat:0.2, cat:'饮品冲调' },
  { name:'椰子水', emoji:'🥥', carb:3.7, protein:0.7, fat:0.2, cat:'饮品冲调' },
  { name:'豆浆(甜)', emoji:'🥛', carb:6.0, protein:3.0, fat:1.6, cat:'饮品冲调' },
  { name:'咖啡(黑)', emoji:'☕', carb:0.4, protein:0.2, fat:0, cat:'饮品冲调' },
  { name:'拿铁(全脂)', emoji:'☕', carb:5.0, protein:3.3, fat:3.5, cat:'饮品冲调' },
  { name:'奶茶(珍珠)', emoji:'🧋', carb:18.0, protein:1.5, fat:2.5, cat:'饮品冲调' },
  { name:'啤酒', emoji:'🍺', carb:3.4, protein:0.4, fat:0, cat:'饮品冲调' },
  { name:'红酒', emoji:'🍷', carb:2.6, protein:0.1, fat:0, cat:'饮品冲调' },
  { name:'运动饮料', emoji:'🥤', carb:6.0, protein:0, fat:0, cat:'饮品冲调' },
];

// All categories for filtering
const FOOD_DB_CATS = [...new Set(FOOD_DB.map(f => f.cat))];
